### ISSUE TITLE
リンクを踏んでログインが求められたとき、ログイン後にリンクのテキストに飛んでほしい

### ISSUE THREAD

**Issue by ushi3** [narusemotoki/text-n#7]
認証したらtext-nのトップではなく、そのテキストのリンクにリダイレクトしてほしい。

たぶんweb.yamlじゃなくて、アプリ内でハンドリングしてやればできるはず…！

**Comment by narusemotoki** [comment]
参考URL
https://developers.google.com/appengine/docs/python/users/loginurls?hl=ja
